### ISSUE TITLE
Child process crashed not a constructor?

### ISSUE THREAD

**Issue by garethsnaim** [gormanb/homebridge-hivehome-control#6] opened 2024-11-05 22:44 UTC
**Describe Your Problem:**
Its installed and seems to be logged in as it spots one of the radiator controllors, but then the child process crashes, it restarts spots that one rad then crashes, endless loop

`TypeError: this.hiveAccessories[deviceType] is not a constructor
    at HiveHomeControllerPlatform.discoverDevices (/homebridge/node_modules/homebridge-hivehome-control/src/platform.ts:147:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/5/2024, 10:31:57 PM] [homebridge-hivehome-control] Child bridge process ended
[11/5/2024, 10:31:57 PM] [homebridge-hivehome-control] Process Ended. Code: 1, Signal: null
[11/5/2024, 10:32:04 PM] [homebridge-hivehome-control] Restarting Process...
[11/5/2024, 10:32:06 PM] [homebridge-hivehome-control] Launched child bridge with PID 15029
[11/5/2024, 10:32:06 PM] Registering platform 'homebridge-hivehome-control.HiveHomeController'
[11/5/2024, 10:32:06 PM] [homebridge-hivehome-control] Loaded homebridge-hivehome-control v1.0.3 child bridge successfully
[11/5/2024, 10:32:06 PM] Loaded 1 cached accessories from cachedAccessories.0E7F2D9EA33C.
[11/5/2024, 10:32:06 PM] [homebridge-hivehome-control] Loading accessory from cache: Alfies Radiator undefined
[11/5/2024, 10:32:06 PM] Homebridge v1.8.5 (HAP v0.12.3) (homebridge-hivehome-control) is running on port 37317.
[11/5/2024, 10:32:06 PM] `

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

`{
    "hiveUsername": "xxxx",
    "hivePassword": "xxx",
    "deviceGroupKey": "xxx",
    "deviceKey": "xxx",
    "devicePassword": "xxx",
    "hotWaterBoostMins": 60,
    "heatingBoostMins": 60,
    "heatingBoostTemp": 21,
    "enableDebugLog": false,
    "_bridge": {
        "username": "0E:7F:2D:9E:A3:3C",
        "port": 37317
    },
    "platform": "HiveHomeController"
}`

**Screenshots:**

**Environment:**

1.0.3. Also tried beta, same issue
1.8.5 homebridge version
Node.js Version I dont know what this is
NPM Version, I dont know what this is
Operating System Unraid in a docker

**Comment by gormanb** [comment] 2024-12-18 23:29
Hi @garethsnaim - this issue is a duplicate of #5, which should be resolved in the newly-released `v1.0.4` of the plugin. Please give that a try, and feel free to re-open this ticket if you're still having problems.

**Closed as duplicate by gormanb** 2024-12-18 23:29 UTC
Labels: question
